name 'jenkins_config'
maintainer 'Bob'
maintainer_email 'ananda.manoharan@nclouds.com'
license 'all_rights'
description 'Installs/Configures jenkins_config'
long_description 'Installs/Configures jenkins_config'
version '1.0.0'

depends 'jenkins', '~> 2.5.0'
depends 'java', '~> 1.39.0'
